[build]
  # आपण 'client' फोल्डरला बेस मानत आहोत
  base = "client"
  
  # आता आपण आधीच 'client' मध्ये आहोत, त्यामुळे 'cd client' ची गरज नाही
  command = "npm install && npm run build"
  
  # 'client' फोल्डरच्या आत तयार होणारे 'build' फोल्डर निवडा
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200